FROM golang:1.14
RUN mkdir /SampleEC-docker
WORKDIR /SampleEC-docker

RUN apt-get update \
    && apt-get install -y mariadb-client

COPY . ./

RUN CGO_ENABLED=0 go build -o routes routes.go

CMD ["./main"]
