version: "3"
services:
  app:
    container_name: SampleEC-app
    hostname: application-server
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/go/src/test-docker
    depends_on:
      - mysql
  mysql:
    container_name: SampleEC-db
    hostname: db-server
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: thamen1451
      MYSQL_USER: root
      MYSQL_PASSWORD: thamen1451
      MYSQL_ROOT_PASSWORD: thamen1451
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
